package com.dantesinferno.game;

import android.app.Activity;
import android.app.AlertDialog;
import android.app.ProgressDialog;
import android.content.Context;
import android.content.Intent;
import android.content.pm.PackageInfo;
import android.content.pm.PackageManager;
import android.net.Uri;
import android.os.Build;
import android.os.Handler;
import android.os.Looper;
import android.provider.Settings;
import android.util.Log;
import android.widget.Toast;

import androidx.core.content.FileProvider;

import org.json.JSONArray;
import org.json.JSONObject;

import java.io.BufferedInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

public final class AppUpdater {

    private static final String TAG = "AppUpdater";
    // Queries all releases (including pre-releases generated by CI/CD)
    private static final String GITHUB_RELEASES_API =
        "https://api.github.com/repos/WINDROID-EMU/Dantes-inferno-Android/releases";
    private static final long MAX_APK_SIZE = 450L * 1024 * 1024; // 450 MB safety limit

    private static final ExecutorService EXECUTOR = Executors.newSingleThreadExecutor();
    private static final Handler MAIN_HANDLER = new Handler(Looper.getMainLooper());

    public interface ProgressListener {
        void onProgress(long bytesRead, long totalBytes, int percent);
    }

    public static final class UpdateInfo {
        public final String tagName;
        public final String title;
        public final String notes;
        public final String apkUrl;
        public final long apkSize;

        public UpdateInfo(String tagName, String title, String notes, String apkUrl, long apkSize) {
            this.tagName = tagName;
            this.title = title;
            this.notes = notes;
            this.apkUrl = apkUrl;
            this.apkSize = apkSize;
        }
    }

    public static final class CheckResult {
        public final UpdateInfo updateInfo;
        public final boolean isNewer;
        public final String installedVersion;

        public CheckResult(UpdateInfo updateInfo, boolean isNewer, String installedVersion) {
            this.updateInfo = updateInfo;
            this.isNewer = isNewer;
            this.installedVersion = installedVersion;
        }
    }

    private AppUpdater() {}

    /**
     * Checks if a release with an Android APK is available on GitHub Releases.
     */
    public static CheckResult checkForUpdate(Context context) throws Exception {
        HttpURLConnection conn = (HttpURLConnection) new URL(GITHUB_RELEASES_API).openConnection();
        conn.setRequestProperty("Accept", "application/vnd.github.v3+json");
        conn.setRequestProperty("User-Agent", "DantesInferno-Android-Updater");
        conn.setConnectTimeout(12000);
        conn.setReadTimeout(12000);

        int responseCode = conn.getResponseCode();
        if (responseCode != HttpURLConnection.HTTP_OK) {
            throw new IOException("GitHub API retornou código HTTP: " + responseCode);
        }

        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        try (InputStream in = conn.getInputStream()) {
            byte[] buf = new byte[8192];
            int r;
            while ((r = in.read(buf)) != -1) {
                baos.write(buf, 0, r);
            }
        }

        String jsonStr = new String(baos.toByteArray(), StandardCharsets.UTF_8);
        JSONArray releasesArray = new JSONArray(jsonStr);

        UpdateInfo foundRelease = null;

        // Iterate through recent releases to find the latest one that has an APK
        for (int i = 0; i < releasesArray.length(); i++) {
            JSONObject release = releasesArray.getJSONObject(i);
            String tagName = release.optString("tag_name", "");
            String title = release.optString("name", tagName);
            String body = release.optString("body", "");

            JSONArray assets = release.optJSONArray("assets");
            String apkUrl = null;
            long apkSize = 0;

            if (assets != null) {
                for (int j = 0; j < assets.length(); j++) {
                    JSONObject asset = assets.getJSONObject(j);
                    String name = asset.optString("name", "");
                    if (name.endsWith(".apk")) {
                        apkUrl = asset.optString("browser_download_url", null);
                        apkSize = asset.optLong("size", 0);
                        if (name.contains("dantes_inferno") || name.contains("arm64")) {
                            break;
                        }
                    }
                }
            }

            if (apkUrl != null) {
                foundRelease = new UpdateInfo(tagName, title, body, apkUrl, apkSize);
                break;
            }
        }

        if (foundRelease == null) {
            throw new IOException("Nenhuma release com APK do Android foi encontrada no repositório.");
        }

        // Compare installed version vs found release
        PackageManager pm = context.getPackageManager();
        PackageInfo pInfo = pm.getPackageInfo(context.getPackageName(), 0);
        String installedVersionName = pInfo.versionName != null ? pInfo.versionName : "1.0.0";

        boolean newer = isNewerVersion(foundRelease.tagName, installedVersionName);
        return new CheckResult(foundRelease, newer, installedVersionName);
    }

    public static boolean isNewerVersion(String releaseTag, String currentVersion) {
        String cleanTag = releaseTag.replaceAll("^[vV]", "").trim();
        String cleanCurrent = currentVersion.replaceAll("^[vV]", "").trim();

        if (cleanTag.equalsIgnoreCase(cleanCurrent)) {
            return false;
        }

        // Extract base semantic version (e.g. 1.0.0 from 1.0.0-build.2)
        String tagSemVer = cleanTag.split("-")[0];
        String currSemVer = cleanCurrent.split("-")[0];

        String[] tagParts = tagSemVer.split("\\.");
        String[] currParts = currSemVer.split("\\.");

        int length = Math.max(tagParts.length, currParts.length);
        for (int i = 0; i < length; i++) {
            int t = i < tagParts.length ? parseNumber(tagParts[i]) : 0;
            int c = i < currParts.length ? parseNumber(currParts[i]) : 0;
            if (t > c) return true;
            if (t < c) return false;
        }

        // If semver is equal (e.g. 1.0.0 vs 1.0.0-build.2):
        int tagBuild = extractBuildNumber(cleanTag);
        int currBuild = extractBuildNumber(cleanCurrent);
        if (tagBuild > currBuild) {
            return true;
        }

        return false;
    }

    private static int parseNumber(String s) {
        try {
            return Integer.parseInt(s.replaceAll("\\D.*", ""));
        } catch (Exception e) {
            return 0;
        }
    }

    private static int extractBuildNumber(String s) {
        if (!s.contains("build.")) {
            return 0;
        }
        try {
            return Integer.parseInt(s.substring(s.indexOf("build.") + 6).replaceAll("\\D.*", ""));
        } catch (Exception e) {
            return 0;
        }
    }

    /**
     * Downloads the APK file to cache directory with progress.
     */
    public static File downloadApk(Context context, UpdateInfo info, ProgressListener listener) throws Exception {
        File updateDir = new File(context.getCacheDir(), "updates");
        if (!updateDir.exists() && !updateDir.mkdirs()) {
            throw new IOException("Falha ao criar diretório de updates em cache.");
        }

        File targetApk = new File(updateDir, "dantes_inferno_update.apk");
        File partialApk = new File(updateDir, "dantes_inferno_update.apk.part");

        if (partialApk.exists()) partialApk.delete();
        if (targetApk.exists()) targetApk.delete();

        HttpURLConnection conn = (HttpURLConnection) new URL(info.apkUrl).openConnection();
        conn.setRequestProperty("User-Agent", "DantesInferno-Android-Updater");
        conn.setConnectTimeout(15000);
        conn.setReadTimeout(30000);
        conn.setInstanceFollowRedirects(true);

        int code = conn.getResponseCode();
        // Handle manual redirect if needed
        if (code == HttpURLConnection.HTTP_MOVED_PERM || code == HttpURLConnection.HTTP_MOVED_TEMP || code == 307 || code == 308) {
            String redirectUrl = conn.getHeaderField("Location");
            if (redirectUrl != null) {
                conn = (HttpURLConnection) new URL(redirectUrl).openConnection();
                conn.setRequestProperty("User-Agent", "DantesInferno-Android-Updater");
                code = conn.getResponseCode();
            }
        }

        if (code != HttpURLConnection.HTTP_OK) {
            throw new IOException("Servidor retornou código HTTP " + code + " ao baixar o APK.");
        }

        long contentLength = conn.getContentLengthLong();
        if (contentLength <= 0 && info.apkSize > 0) {
            contentLength = info.apkSize;
        }

        if (contentLength > MAX_APK_SIZE) {
            throw new IOException("Tamanho do arquivo recebido excede o limite seguro de 450 MB.");
        }

        long downloaded = 0;
        byte[] buffer = new byte[64 * 1024];

        try (InputStream in = new BufferedInputStream(conn.getInputStream());
             FileOutputStream out = new FileOutputStream(partialApk)) {
            int read;
            while ((read = in.read(buffer)) != -1) {
                out.write(buffer, 0, read);
                downloaded += read;
                if (listener != null && contentLength > 0) {
                    int percent = (int) ((downloaded * 100) / contentLength);
                    listener.onProgress(downloaded, contentLength, percent);
                }
            }
            out.flush();
        }

        if (!partialApk.renameTo(targetApk)) {
            throw new IOException("Falha ao finalizar o arquivo APK baixado.");
        }

        return targetApk;
    }

    /**
     * Prompts Android package installer via FileProvider.
     */
    public static void installApk(Activity activity, File apkFile) {
        if (apkFile == null || !apkFile.exists()) {
            Toast.makeText(activity, "Arquivo de atualização não encontrado.", Toast.LENGTH_SHORT).show();
            return;
        }

        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            if (!activity.getPackageManager().canRequestPackageInstalls()) {
                new AlertDialog.Builder(activity)
                    .setTitle("Permissão Necessária")
                    .setMessage("Para atualizar o Dante's Inferno, conceda a permissão de instalar aplicativos desta fonte nas Configurações.")
                    .setPositiveButton("Configurações", (d, w) -> {
                        Intent intent = new Intent(Settings.ACTION_MANAGE_UNKNOWN_APP_SOURCES,
                            Uri.parse("package:" + activity.getPackageName()));
                        activity.startActivity(intent);
                    })
                    .setNegativeButton("Cancelar", null)
                    .show();
                return;
            }
        }

        try {
            Uri apkUri = FileProvider.getUriForFile(
                activity,
                activity.getPackageName() + ".fileprovider",
                apkFile
            );

            Intent intent = new Intent(Intent.ACTION_VIEW);
            intent.setDataAndType(apkUri, "application/vnd.android.package-archive");
            intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
            intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            activity.startActivity(intent);
        } catch (Exception e) {
            Log.e(TAG, "Erro ao iniciar instalador do APK", e);
            Toast.makeText(activity, "Erro ao abrir instalador do APK: " + e.getMessage(), Toast.LENGTH_LONG).show();
        }
    }

    /**
     * Helper method to trigger the update check flow with UI dialogs.
     */
    public static void checkAndPromptUpdate(Activity activity, boolean userInitiated) {
        ProgressDialog checkDialog = new ProgressDialog(activity);
        checkDialog.setMessage("Verificando atualizações no GitHub...");
        checkDialog.setCancelable(false);
        if (userInitiated) {
            checkDialog.show();
        }

        EXECUTOR.execute(() -> {
            try {
                CheckResult result = checkForUpdate(activity);
                MAIN_HANDLER.post(() -> {
                    if (checkDialog.isShowing()) checkDialog.dismiss();

                    if (result != null && result.updateInfo != null) {
                        UpdateInfo info = result.updateInfo;
                        if (result.isNewer) {
                            String msg = "Uma nova versão está disponível: " + info.tagName + "\n\n" +
                                         (info.notes.isEmpty() ? "Melhorias e correções de desempenho." : info.notes);
                            new AlertDialog.Builder(activity)
                                .setTitle("Atualização Encontrada!")
                                .setMessage(msg)
                                .setPositiveButton("Atualizar Agora", (d, w) -> startDownloadFlow(activity, info))
                                .setNegativeButton("Mais Tarde", null)
                                .show();
                        } else if (userInitiated) {
                            new AlertDialog.Builder(activity)
                                .setTitle("Versão Atualizada")
                                .setMessage("Você já está executando a versão mais recente (" + info.tagName + ").\n\nDeseja baixar e reinstalar o APK mesmo assim?")
                                .setPositiveButton("Reinstalar", (d, w) -> startDownloadFlow(activity, info))
                                .setNegativeButton("Fechar", null)
                                .show();
                        }
                    } else if (userInitiated) {
                        Toast.makeText(activity, "Você já está executando a versão mais recente!", Toast.LENGTH_SHORT).show();
                    }
                });
            } catch (Exception e) {
                Log.w(TAG, "Falha na verificação de atualização: " + e.getMessage());
                MAIN_HANDLER.post(() -> {
                    if (checkDialog.isShowing()) checkDialog.dismiss();
                    if (userInitiated) {
                        Toast.makeText(activity, "Não foi possível verificar atualizações: " + e.getMessage(), Toast.LENGTH_LONG).show();
                    }
                });
            }
        });
    }

    private static void startDownloadFlow(Activity activity, UpdateInfo info) {
        ProgressDialog downloadDialog = new ProgressDialog(activity);
        downloadDialog.setTitle("Baixando Atualização");
        downloadDialog.setMessage("Baixando " + info.tagName + "...");
        downloadDialog.setProgressStyle(ProgressDialog.STYLE_HORIZONTAL);
        downloadDialog.setMax(100);
        downloadDialog.setProgress(0);
        downloadDialog.setCancelable(false);
        downloadDialog.show();

        EXECUTOR.execute(() -> {
            try {
                File downloadedApk = downloadApk(activity, info, (read, total, percent) -> {
                    MAIN_HANDLER.post(() -> {
                        downloadDialog.setProgress(percent);
                        float mbDownloaded = read / (1024f * 1024f);
                        float mbTotal = total / (1024f * 1024f);
                        downloadDialog.setMessage(String.format("Baixando: %.1f MB / %.1f MB (%d%%)", mbDownloaded, mbTotal, percent));
                    });
                });

                MAIN_HANDLER.post(() -> {
                    if (downloadDialog.isShowing()) downloadDialog.dismiss();
                    installApk(activity, downloadedApk);
                });
            } catch (Exception e) {
                Log.e(TAG, "Erro ao baixar APK", e);
                MAIN_HANDLER.post(() -> {
                    if (downloadDialog.isShowing()) downloadDialog.dismiss();
                    new AlertDialog.Builder(activity)
                        .setTitle("Erro no Download")
                        .setMessage("Falha ao baixar a atualização: " + e.getMessage())
                        .setPositiveButton("OK", null)
                        .show();
                });
            }
        });
    }
}
